return {
    ["luassert.compatibility"] = require("src/compatibility.lua"),
    ["luassert.state"] = require("src/state.lua"),
    ["luassert.util"] = require("src/util.lua"),
    ["luassert.spy"] = require("src/spy.lua"),
    ["luassert.stub"] = require("src/stub.lua"),
    ["luassert.assert"] = require("src/assert.lua"),
    ["luassert.modifiers"] = require("src/modifiers.lua"),
    ["luassert.assertions"] = require("src/assertions.lua"),
    ["luassert.namespaces"] = require("src/namespaces.lua"),
    ["luassert.match"] = require("src/match.lua"),
    ["luassert.mock"] = require("src/mock.lua"),
    ["luassert.init"] = require("src/init.lua"),
    ["luassert.matchers.init"] = require("src/matchers/init.lua"),
    ["luassert.matchers.core"] = require("src/matchers/core.lua"),
    ["luassert.matchers.composite"] = require("src/matchers/composite.lua"),
    ["luassert.formatters.init"] = require("src/formatters/init.lua"),
    ["luassert.formatters.binarystring"] = require("src/formatters/binarystring.lua"),
    ["luassert.languages.en"] = require("src/languages/en.lua"),
    ["luassert.languages.ar"] = require("src/languages/ar.lua"),
    ["luassert.languages.fr"] = require("src/languages/fr.lua"),
    ["luassert.languages.nl"] = require("src/languages/nl.lua"),
    ["luassert.languages.ru"] = require("src/languages/ru.lua"),
    ["luassert.languages.ua"] = require("src/languages/ua.lua"),
    ["luassert.languages.zh"] = require("src/languages/zh.lua"),
    ["luassert.languages.ja"] = require("src/languages/ja.lua"),


}
