local Lexer = require("Lexers/Lexer"):new()

Lexer:Keyword("and", "And")
Lexer:Keyword("or", "Or")
Lexer:Keyword("not", "Not")
Lexer:Keyword("for", "For")
Lexer:Keyword("in", "In")
Lexer:Keyword("do", "Do")
Lexer:Keyword("end", "End")
Lexer:Keyword("if", "If")
Lexer:Keyword("then", "Then")
Lexer:Keyword("else", "Else")
Lexer:Keyword("elseif", "ElseIf")
Lexer:Keyword("while", "While")
Lexer:Keyword("repeat", "Repeat")
Lexer:Keyword("until", "Until")
Lexer:Keyword("function", "Function")
Lexer:Keyword("local", "Local")
Lexer:Keyword("return", "Return")
Lexer:Keyword("break", "Break")
Lexer:Keyword("true", "True")
Lexer:Keyword("false", "False")
Lexer:Keyword("nil", "Nil")

Lexer:Add("%d+%.?%d*", "Number")
Lexer:Add("'[^\n\r]*'", "String")
Lexer:Add("\"[^\n\r]*\"", "String")
Lexer:Add("%[=*%[.-%]=*%]", "String")

Lexer:Add("%-%-%[=*%[.-%]=*%]", "Comment")
Lexer:Add("%-%-[^\n\r]*", "Comment")

Lexer:Add("%.%.%.", "Ellipse")
Lexer:Add("%(", "LeftParen")
Lexer:Add("%)", "RightParen")
Lexer:Add("{", "LeftBrace")
Lexer:Add("}", "RightBrace")
Lexer:Add("%[", "LeftBracket")
Lexer:Add("%]", "RightBracket")
Lexer:Add(";", "Semicolon")
Lexer:Add(":", "Colon")
Lexer:Add("%.%.", "Concat")
Lexer:Add("%.", "Dot")
Lexer:Add(",", "Comma")

Lexer:Add("==", "EqualsEquals")
Lexer:Add("~=", "TidleEquals")
Lexer:Add("<=", "LessThanEquals")
Lexer:Add(">=", "GreaterThanEquals")
Lexer:Add("<", "LessThan")
Lexer:Add(">", "GreaterThan")

Lexer:Add("+", "Plus")
Lexer:Add("%-", "Minus")
Lexer:Add("*", "Star")
Lexer:Add("/", "Slash")
Lexer:Add("%%", "Percent")
Lexer:Add("%^", "Caret")
Lexer:Add("#", "Hash")
Lexer:Add("=", "Equals")

Lexer:Add("[a-zA-Z_][a-zA-Z0-9_]*", "Identifier")
Lexer:Add("[ \t]*[\r?\n]?", "Whitespace")

return Lexer