-- This Script is Part of the Cyber Obfuscator by DailyBGL
--
-- config.lua
--
-- In this Script, some Global config Variables are defined
-- These may be changed

-- You are not allowed to change the following Variables
local NAME    = "CyberFuscator";
local REVISION = "Alpha";
local VERSION = "v0.1";
local BY      = "DailyBGL#5936";
local DISCORD = "https://discord.gg/FDyj7Kbx7z"

for _, currArg in pairs(arg) do
	if currArg == "--CI" then
		local releaseName = string.gsub(string.format("%s %s %s", NAME, REVISION, VERSION), "%s", "-")
		print(releaseName)
	end
	
	if currArg == "--FullVersion" then
		print(VERSION)
	end
end

-- Config Starts here
return {
	Name = NAME,
	NameUpper = string.upper(NAME),
	NameAndVersion = string.format("%s %s", NAME, VERSION),
	Version = VERSION;
	Revision = REVISION;
	Watermark = string.format("OBFUSCATOR USING %s %s %s by %s | %s", NAME, REVISION, VERSION, BY, DISCORD); -- You are not allowed to edit the watermark
	-- Config Starts Here
	IdentPrefix = "__cyber_"; -- The Prefix used for Identifiers generated by cyber. NOTE: There should be no identifiers in the script to be obfuscated starting with that prefix, because that can lead to weird bugs
	
	SPACE = " "; -- The Whitespace to be used by the unparser
	TAB   = "\t"; -- The Tab Whitespace to be used by the unparser for pretty printing
}